name: CI/CD

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**.md'

jobs:

  build-jvm:
    env:
      DOCKER_ACCOUNT: sogis
      DOCKER_REPO: ilivalidator-web-service
      DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}} 
      BUILD_NUMBER: ${{ github.run_number }}
      MAJOR_NUMBER: "3"
      MINOR_NUMBER: "0"

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:

      - name: Print new build number
        run: echo "Build number is $BUILD_NUMBER"

      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'liberica'
          java-version: '21'
          cache: 'maven'

      - name: Test and build Jar
        run: |
          ./mvnw -Penv-test clean test -DexcludedGroups="docker"
          ./mvnw -Penv-prod clean package -DexcludedGroups="docker"
          ls -la ilivalidator-web-service-server/target

      - name: List Docker images
        run: |
          docker images

      - name: Test Docker image
        run: ./mvnw test -Dgroups="docker"

      - name: Login to Docker Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: ${{ (github.ref == 'refs/heads/main') && (github.event_name != 'pull_request') && !env.ACT }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ (github.ref == 'refs/heads/main') && (github.event_name != 'pull_request') && !env.ACT }}

      - name: Set up QEMU for amd64 and arm64
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/amd64,linux/arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Multi-platform build and push to Docker Container Registry and Github Container Registry
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          context: ilivalidator-web-service-server
          file: ilivalidator-web-service-server/Dockerfile.ubi-layered
          labels: ${{ steps.meta.outputs.labels }}
          pull: true
          push: ${{ (github.ref == 'refs/heads/main') && (github.event_name != 'pull_request') && !env.ACT }}
          tags: |
            ${{ env.DOCKER_ACCOUNT }}/${{ env.DOCKER_REPO }}:latest
            ${{ env.DOCKER_ACCOUNT }}/${{ env.DOCKER_REPO }}:${{ env.MAJOR_NUMBER }}.${{ env.MINOR_NUMBER }}.${{ env.BUILD_NUMBER }}
            ${{ env.DOCKER_ACCOUNT }}/${{ env.DOCKER_REPO }}:${{ env.MAJOR_NUMBER }}.${{ env.MINOR_NUMBER }}
            ${{ env.DOCKER_ACCOUNT }}/${{ env.DOCKER_REPO }}:${{ env.MAJOR_NUMBER }}
            ghcr.io/${{ env.DOCKER_ACCOUNT }}/${{ env.DOCKER_REPO }}:latest
            ghcr.io/${{ env.DOCKER_ACCOUNT }}/${{ env.DOCKER_REPO }}:${{ env.MAJOR_NUMBER }}.${{ env.MINOR_NUMBER }}.${{ env.BUILD_NUMBER }}
            ghcr.io/${{ env.DOCKER_ACCOUNT }}/${{ env.DOCKER_REPO }}:${{ env.MAJOR_NUMBER }}.${{ env.MINOR_NUMBER }}
            ghcr.io/${{ env.DOCKER_ACCOUNT }}/${{ env.DOCKER_REPO }}:${{ env.MAJOR_NUMBER }}
